### ISSUE TITLE
I am new to github.

### ISSUE THREAD

**Issue by Vishal18v** [abhilashk433/Hacktoberfest-2018#10]
i dont know terminology issue. can u help

**Comment by abhilashk433** [comment]
Yes @Vishal18v . I will help you. Issues are a great way to keep track of tasks, enhancements, and bugs for your projects. They’re kind of like email—except they can be shared and discussed with the rest of your team. Most software projects have a bug tracker of some kind. GitHub’s tracker is called Issues, and has its own section in every repository. Check out the readme file for more info.
